### ISSUE TITLE
Error when I try to pay

### ISSUE THREAD

**Issue by dfranczuk** [BitBagCommerce/SyliusPrzelewy24Plugin#2]
Error message:
`Argument 1 passed to Payum\Core\Gateway::addAction() must implement interface Payum\Core\Action\ActionInterface, string given, called in C:\xampp2\htdocs\payme\vendor\payum\payum\src\Payum\Core\CoreGatewayFactory.php on line 224`

Any ideas how to solve this?

**Comment by patrick477** [comment]
Fixed https://github.com/BitBagCommerce/SyliusPrzelewy24Plugin/releases/tag/v1.0.3
